version: '3'

services:
  traefik:
    image: traefik:v3.1
    networks:
      - traefiknetwork
    ports:
      - "80:80"
      - "443:443"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml:ro
      - ./config.yaml:/config.yaml:ro
      - ./certs:/etc/certs:ro
      - ./acme.json:/acme.json
      - ./logs:/var/log
    restart: unless-stopped

networks:
    traefiknetwork:
        name: traefiknetwork
        external: true