
providers:
  docker: 
    exposedByDefault: false
    network: traefiknetwork

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true
  debug: true

log: true
accessLog:
  filepath: /var/log/access.log

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: your-email@example.com
#       storage: acme.json
#       httpChallenge:
#         entryPoint: web

# metrics:
#   prometheus: {}